"use client";

import { createEntityStore } from "@/stores/create-entity-store";
import type { InspectionRoute } from "@/types";

const mockRoutes: InspectionRoute[] = [
  {
    id: "route_1",
    company_id: "comp_1",
    name: "Morning Safety Walk",
    description: "Daily walkthrough of main production floor",
    status: "active",
    recurrence: "daily",
    assigned_to_user_id: null,
    assigned_to_team_id: null,
    checkpoints: [
      {
        id: "cp_1",
        asset_id: "asset_1",
        order: 1,
        label: "Check conveyor belt tension",
        check_type: "visual",
        acceptable_min: null,
        acceptable_max: null,
        unit: null,
        instructions: "Look for slack or misalignment in the belt",
        required: true,
      },
      {
        id: "cp_2",
        asset_id: "asset_4",
        order: 2,
        label: "Fire extinguisher pressure gauge",
        check_type: "measurement",
        acceptable_min: 100,
        acceptable_max: 175,
        unit: "psi",
        instructions: "Gauge should be in the green zone (100-175 psi)",
        required: true,
      },
      {
        id: "cp_3",
        asset_id: "asset_2",
        order: 3,
        label: "Forklift horn and lights",
        check_type: "functional",
        acceptable_min: null,
        acceptable_max: null,
        unit: null,
        instructions: "Test horn, headlights, brake lights, and reverse beeper",
        required: true,
      },
      {
        id: "cp_4",
        asset_id: "asset_5",
        order: 4,
        label: "Motor temperature",
        check_type: "measurement",
        acceptable_min: 60,
        acceptable_max: 80,
        unit: "°C",
        instructions: "Use infrared thermometer on motor housing",
        required: true,
      },
    ],
    created_by: "user_1",
    created_at: "2024-06-01T08:00:00Z",
    updated_at: "2024-06-01T08:00:00Z",
  },
  {
    id: "route_2",
    company_id: "comp_1",
    name: "Weekly Equipment Check",
    description: "Thorough weekly inspection of critical machinery",
    status: "active",
    recurrence: "weekly",
    assigned_to_user_id: null,
    assigned_to_team_id: null,
    checkpoints: [
      {
        id: "cp_5",
        asset_id: "asset_1",
        order: 1,
        label: "Conveyor motor vibration",
        check_type: "auditory",
        acceptable_min: null,
        acceptable_max: null,
        unit: null,
        instructions: "Listen for unusual rattling, grinding, or humming",
        required: true,
      },
      {
        id: "cp_6",
        asset_id: "asset_6",
        order: 2,
        label: "Belt tensioner hydraulic pressure",
        check_type: "measurement",
        acceptable_min: 2000,
        acceptable_max: 3000,
        unit: "psi",
        instructions: "Read pressure gauge on tensioner unit",
        required: true,
      },
      {
        id: "cp_7",
        asset_id: "asset_3",
        order: 3,
        label: "Forklift #2 safety check",
        check_type: "safety",
        acceptable_min: null,
        acceptable_max: null,
        unit: null,
        instructions: "Check seatbelt, overhead guard, forks for cracks",
        required: true,
      },
    ],
    created_by: "user_1",
    created_at: "2024-06-01T08:00:00Z",
    updated_at: "2024-06-01T08:00:00Z",
  },
];

const store = createEntityStore<InspectionRoute>("harmoniq_inspection_routes", mockRoutes);

export const InspectionRoutesProvider = store.Provider;
export const useInspectionRoutesStore = store.useStore;
